# Generated by Django 5.2.7 on 2025-10-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_at',
        ),
    ]
